### ISSUE TITLE
Attempting to compile on Raspberry Pi: librt.so issue

### ISSUE THREAD

**Issue by NHMatt** [covertcodes/freqwatch#5]
I'm not quite sure what is going awry here at first glance...

pi@raspberrypi ~/freqwatch/rtl_fm_new $ make
gcc -lpthread -l rtlsdr -lm -lmysqlclient -o rtl_fm rtl_fm.c convenience/convenience.c
/usr/bin/ld: /tmp/ccYHkMg5.o: undefined reference to symbol 'clock_gettime@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/librt.so.1: error adding symbols: DSO missing from command line
collect2: ld returned 1 exit status
Makefile:4: recipe for target 'rtl_fm' failed
make: *** [rtl_fm] Error 1

**Comment by covertcodes** [comment]
I'm away from home for awhile and no access to a Pi but: try compliling with -lrt (stands for lib-real-time) instead.  Let me know if it works

**Comment by NHMatt** [comment]
That worked, thanks!
